import {
  faAddressCard,
  faArrowRight,
  faArrowUp,
  faArrowUpLong,
  faAward,
  faBars,
  faBible,
  faBookmark,
  faBookOpen,
  faBullhorn,
  faBuilding,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDays,
  faCamera,
  faCampground,
  faCheckCircle,
  faChevronCircleDown,
  faChevronCircleUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChurch,
  faCloudUploadAlt,
  faClock,
  faComment,
  faComments,
  faCross,
  faCrown,
  faDove,
  faDownload,
  faEdit,
  faEnvelope,
  faExclamationTriangle,
  faExpand,
  faFileAlt,
  faFileUpload,
  faFire,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faGaugeHigh,
  faGift,
  faGlobe,
  faHandHolding,
  faHandHoldingHeart,
  faHandshake,
  faHands,
  faHandsPraying,
  faHeart,
  faHome,
  faHouse,
  faImage,
  faImages,
  faInfoCircle,
  faLeaf,
  faLightbulb,
  faLink,
  faLocationDot,
  faLocationPin,
  faMagnifyingGlass,
  faMapMarker,
  faMapPin,
  faMedal,
  faMountain,
  faMugHot,
  faMusic,
  faNewspaper,
  faPenToSquare,
  faPersonPraying,
  faPhone,
  faPlayCircle,
  faPlus,
  faPlusCircle,
  faPrayingHands,
  faQuoteLeft,
  faQuoteRight,
  faRefresh,
  faRightFromBracket,
  faSave,
  faSeedling,
  faShare,
  faShield,
  faShieldHalved,
  faSignOutAlt,
  faStar,
  faSpinner,
  faTrash,
  faTrashAlt,
  faTrophy,
  faUserFriends,
  faUsers,
  faVideo,
  faXmark
} from "@fortawesome/free-solid-svg-icons"
import { faFacebook, faInstagram, faYoutube } from "@fortawesome/free-brands-svg-icons"

const icons = {
  "fas": {
    "address-card": faAddressCard,
    "arrow-right": faArrowRight,
    "arrow-up": faArrowUp,
    "arrow-up-long": faArrowUpLong,
    "award": faAward,
    "bars": faBars,
    "bible": faBible,
    "bookmark": faBookmark,
    "book-open": faBookOpen,
    "building": faBuilding,
    "bullhorn": faBullhorn,
    "calendar": faCalendar,
    "calendar-alt": faCalendarAlt,
    "calendar-check": faCalendarCheck,
    "calendar-days": faCalendarDays,
    "camera": faCamera,
    "campground": faCampground,
    "check-circle": faCheckCircle,
    "chevron-circle-down": faChevronCircleDown,
    "chevron-circle-up": faChevronCircleUp,
    "chevron-down": faChevronDown,
    "chevron-left": faChevronLeft,
    "chevron-right": faChevronRight,
    "chevron-up": faChevronUp,
    "church": faChurch,
    "clock": faClock,
    "cloud-upload-alt": faCloudUploadAlt,
    "comment": faComment,
    "comments": faComments,
    "cross": faCross,
    "crown": faCrown,
    "dove": faDove,
    "download": faDownload,
    "edit": faEdit,
    "envelope": faEnvelope,
    "expand": faExpand,
    "file-alt": faFileAlt,
    "file-upload": faFileUpload,
    "fire": faFire,
    "folder": faFolder,
    "folder-open": faFolderOpen,
    "folder-plus": faFolderPlus,
    "gauge-high": faGaugeHigh,
    "gift": faGift,
    "globe": faGlobe,
    "hand-holding": faHandHolding,
    "hand-holding-heart": faHandHoldingHeart,
    "handshake": faHandshake,
    "hands": faHands,
    "hands-praying": faHandsPraying,
    "heart": faHeart,
    "home": faHome,
    "house": faHouse,
    "image": faImage,
    "images": faImages,
    "info-circle": faInfoCircle,
    "leaf": faLeaf,
    "lightbulb": faLightbulb,
    "link": faLink,
    "location-dot": faLocationDot,
    "location-pin": faLocationPin,
    "magnifying-glass": faMagnifyingGlass,
    "map-marker": faMapMarker,
    "map-pin": faMapPin,
    "medal": faMedal,
    "mountain": faMountain,
    "mug-hot": faMugHot,
    "music": faMusic,
    "newspaper": faNewspaper,
    "pen-to-square": faPenToSquare,
    "person-praying": faPersonPraying,
    "phone": faPhone,
    "play-circle": faPlayCircle,
    "plus": faPlus,
    "plus-circle": faPlusCircle,
    "praying-hands": faPrayingHands,
    "quote-left": faQuoteLeft,
    "quote-right": faQuoteRight,
    "refresh": faRefresh,
    "right-from-bracket": faRightFromBracket,
    "save": faSave,
    "seedling": faSeedling,
    "share": faShare,
    "shield": faShield,
    "shield-halved": faShieldHalved,
    "sign-out-alt": faSignOutAlt,
    "spinner": faSpinner,
    "star": faStar,
    "trash": faTrash,
    "trash-alt": faTrashAlt,
    "triangle-exclamation": faExclamationTriangle,
    "trophy": faTrophy,
    "user-friends": faUserFriends,
    "users": faUsers,
    "video": faVideo,
    "xmark": faXmark,
  },
  "fab": {
    "facebook": faFacebook,
    "instagram": faInstagram,
    "youtube": faYoutube,
  }
}

export const getIcon = ( icon: SolidIcon | BrandIcon ) => {
  if ( icon in icons.fas ) {
    return icons.fas [ icon as SolidIcon ]
  } else if ( icon in icons.fab ) {
    return icons.fab [ icon as BrandIcon ]
  } else {
    console.warn ( `Icon not found: ${icon}` )
    return icons.fas [ "exclamation-triangle" as SolidIcon ]
  }
}

export type BrandIcon = keyof typeof icons.fab
export type SolidIcon = keyof typeof icons.fas

export const solidIconNames: SolidIcon[] = Object.keys ( icons.fas ) as SolidIcon[]
export const brandIconNames: BrandIcon[] = Object.keys ( icons.fab ) as BrandIcon[]